<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Today' => 'Aujourd\'hui',
    'Delete' => 'Supprimer',
    'Edit' => 'Modifier',
    'Save' => 'Enregistrer',
    '<strong>Mail</strong> module configuration' => 'Module de configuration de <strong>Courriel</strong>',
    'Allow others to send you private messages' => 'Autoriser les autres utilisateurs à vous envoyer des messages privés',
    'Allow users to start new conversations' => 'Autoriser les utilisateurs à lancer des nouvelles conversations',
    'Conversation' => 'Conversation',
    'Created At' => 'Créé le',
    'Created By' => 'Créé par',
    'Edit message...' => 'Modifier le message...',
    'Is Originator' => 'Est à l\'origine',
    'Last Viewed' => 'Dernière lecture',
    'Leave fields blank in order to disable a restriction.' => 'Laisser vide pour désactiver une restriction.',
    'Max messages allowed per day' => 'Nombre maximum de messages autorisés par jour',
    'Max number of messages allowed for a new user per day' => 'Nombre maximum de messages autorisés par jour pour un nouvel utilisateur',
    'Max number of new conversations allowed for a new user per day' => 'Nombre maximum de nouvelles conversations autorisées par jour pour un nouvel utilisateur',
    'Max number of new conversations allowed for a user per day' => 'Nombre maximum de nouvelles conversations autorisées par utilisateur par jour',
    'Message' => 'Message',
    'Messages' => 'Messages',
    'Receive Notifications when someone opens a new conversation.' => 'Recevoir une notification lorsqu\'on lance une conversation.',
    'Receive Notifications when someone sends you a message.' => 'Recevoir une notification lorsqu\'on m\'envoie un message.',
    'Receive private messages' => 'Recevoir des messages privés',
    'Seperate restrictions for new users' => 'Restrictions spécifiques pour les nouveaux utilisateurs',
    'Show menu item in top Navigation' => 'Montrer l\'élément de menu dans la navigation supérieure',
    'Start new conversations' => 'Lancer des nouvelles conversations',
    'This user is already participating in this conversation.' => 'L\'utilisateur participe déjà à cette conversation.',
    'Title' => 'Titre',
    'Until a user is member since (days)' => 'Tant que l\'utilisateur a une ancienneté inférieure à (jours)',
    'Updated At' => 'Mis à jour le',
    'Updated By' => 'Mis à jour par',
    'User' => 'Utilisateur',
    'Write a message...' => 'Écrire un message...',
    'You are not allowed to start a conversation with this user.' => 'Vous n\'êtes pas autorisé à démarrer une conversation avec cet utilisateur.',
    'You\'ve exceeded your daily amount of new conversations.' => 'Vous avez dépassé votre nombre quotidien autorisé de nouvelles conversations.',
];
