<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accounting' => '',
    'Accounting system for projects' => '',
    'Accounts' => '',
    'Allows the user to create an own account' => '',
    'Amount' => '',
    'Asset' => '',
    'Asset(s) balance' => '',
    'Available' => '',
    'Buy this Product' => '',
    'Change' => '',
    'Create account' => '',
    'Created At' => '',
    'Created By' => '',
    'Crowd Funding' => '',
    'Date' => '',
    'Deadline' => '',
    'Description' => '',
    'Detailed Description' => '',
    'Discount for coins' => '',
    'Discount in %' => '',
    'Ethereum' => '',
    'Exchange rate' => '',
    'ID' => '',
    'Insuffient funds.' => '',
    'Manager' => '',
    'Marketplace' => '',
    'Maximum 4 decimal places.' => '',
    'Maximum offered amount' => '',
    'Name' => '',
    'Needs & Commitments' => '',
    'No assets issued yet.' => '',
    'Offer' => '',
    'Offer Account' => '',
    'Offer Type' => '',
    'Offered asset' => '',
    'Owner' => '',
    'Payment Type' => '',
    'Per Day' => '',
    'Per Hour' => '',
    'Per Service' => '',
    'Per Unit' => '',
    'Please select an different account!' => '',
    'Price' => '',
    'Price per unit' => '',
    'Products' => '',
    'Rate: 1 to ' => '',
    'Recipient' => '',
    'Related account' => '',
    'Request' => '',
    'Requested Coin' => '',
    'Requested asset' => '',
    'Sender' => '',
    'Sender account' => '',
    'Shareholdings:' => '',
    'Space' => '',
    'Space ID' => '',
    'Status' => '',
    'Title' => '',
    'Total Amount' => '',
    'Total price in coins' => '',
    'Unavailable' => '',
    'User' => '',
    'User ID' => '',
    'Wanted' => '',
    'You cannot transfer this type of asset.' => '',
];
