<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Your Project' => 'Ajouter votre projet',
    'Add a challenge!' => 'Ajouter un challenge',
    'All Products' => 'Tous les produits',
    'All Projects' => 'Tous les projets',
    'Any project Issued COIN' => 'Tout forme de COIN crée',
    'Challenge Image (MAXIMUM FILE SIZE IS 500kb)' => 'Image du challenge (MAXIMUM 500kb)',
    'Challenge owner' => 'Proprietaire du challenge',
    'Create Challenge' => 'Créer un challenge',
    'Created At' => 'Crée le',
    'Created By' => 'Crée par',
    'Currently there are no challenges.' => 'Actuallement, il n\'ya pas de challenge',
    'Currently there are no received submissions.' => 'Actuellement, il n\'ya pas de soumissions recu.',
    'Description' => '',
    'Edit' => 'Modifier',
    'Edit Challenge' => 'Modifier le challenge',
    'Hide unverified Submissions' => 'Cacher les soumissions non verifiés',
    'ID' => '',
    'No rewarding' => 'Pas de récompenses',
    'Please enter your challenge description' => 'Veuillez saisir la description de votre challenge',
    'Please enter your challenge title' => 'Veuillez saisir le titre de votre challenge',
    'Project Must offer' => 'Projet doit offrir',
    'Project owner' => 'Propriétaire du projet',
    'Received Submissions' => 'Soumissions reçus',
    'Receiver' => 'Récepteur',
    'Requested coin' => 'COIN demandées',
    'Save' => 'Sauvegarder',
    'Select coin' => 'Sélectionner les COIN',
    'Select status' => 'Sélectionner le statut',
    'Send message to' => 'Envoyer un message à',
    'Space Challenges' => 'Challenge de l´éspace',
    'Space ID' => 'ID de l\'éspace',
    'Status' => 'Statut',
    'This challenge is closed' => 'Ce challenge est fermé',
    'This challenge is stopped' => 'Ce challenge est arrêté',
    'Title' => 'Titre',
    'for each invested COIN' => 'pour chaque COIN investi',
    'link' => 'lien',
    'of' => 'de',
];
