<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Your Project' => '',
    'Add a challenge!' => '',
    'All Products' => '',
    'All Projects' => '',
    'Any project Issued COIN' => '',
    'Challenge Image (MAXIMUM FILE SIZE IS 500kb)' => '',
    'Challenge owner' => '',
    'Create Challenge' => '',
    'Created At' => '',
    'Created By' => '',
    'Currently there are no challenges.' => '',
    'Currently there are no received submissions.' => '',
    'Description' => '',
    'Edit' => '',
    'Edit Challenge' => '',
    'Hide unverified Submissions' => '',
    'ID' => '',
    'No rewarding' => '',
    'Please enter your challenge description' => '',
    'Please enter your challenge title' => '',
    'Project Must offer' => '',
    'Project owner' => '',
    'Received Submissions' => '',
    'Receiver' => '',
    'Requested coin' => '',
    'Save' => '',
    'Select coin' => '',
    'Select status' => '',
    'Send message to' => '',
    'Space Challenges' => '',
    'Space ID' => '',
    'Status' => '',
    'This challenge is closed' => '',
    'This challenge is stopped' => '',
    'Title' => '',
    'for each invested COIN' => '',
    'link' => '',
    'of' => '',
];
