<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Experience' => 'Ajouter votre expérience',
    'Are you sure about deleting this experience' => 'Êtes-vous sûr de supprimer cette expérience',
    'Delete Experience' => 'Supprimer l\'expérience',
    'Edit Experience' => 'Modifier l\'expérience',
    'Experience' => 'Expérience',
    'Experience Start Date must be greater than End Date' => 'La date de début de l\'expérience doit être postérieure à la date de fin',
    'No experiences found.' => 'Aucune expérience trouvée.',
    'Provide experience details' => 'Ajouter les détails de l\'expérience',
    'Save' => 'Sauvegarder',
    'Select country' => 'Sélectionner le pays',
    'Today' => 'Aujourd\'hui',
];
