<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Crowd</strong> Funding' => '<strong>Crowd</strong> funding',
    '<strong>Crowd</strong> funding' => '<strong>Crowd</strong> funding',
    '<strong>Funding</strong> Invest' => '<strong>Financement</strong> Investisement',
    'Add asset offer' => 'Lancer la campagne de financement',
    'Closed' => 'Fermé',
    'Currently there are no open funding requests.' => 'Actuellement, il n ya pas de demandes de financement ouvertes',
    'Currently there are no running crowd fundings campaigns!' => 'Actuellement, il n ya pas de campagnes de financement participatif en cours!',
    'Day left' => 'Jour restant',
    'Days left' => 'Jours restants',
    'Define exchange rate and maximum' => 'Définir taux de change et maximum',
    'Delete this exchange request' => 'Supprimer cette demande',
    'Determine the exchange rate for which you are willing to trade assets.' => 'A quel taux souhaitez-vous échanger vos COIN?',
    'Edit' => 'Modifier',
    'Gallery' => 'Galerie',
    'Invest in this project' => 'Investir dans ce projet',
    'Next' => 'Suivant',
    'Offering:' => 'Offre',
    'Pay now' => 'Payez maintenant',
    'Please enter your campaign deadline' => 'S\'il vous plait enter votre date limite de campagne',
    'Please enter your campaign description' => 'Veuillez saisir une brève description de votre campagne',
    'Please enter your campaign needs & commitments' => 'S\'il vous plaît entrer plus de détails sur votre projet',
    'Please enter your campaign title' => 'Veuillez entrer le titre de votre campagne',
    'Please note that first picture will be used as cover for your crowdfunding campaign.' => 'Veuillez noter que la premiére photo servira de couverture à votre campagne de financement participatif.',
    'Project by' => 'Projet de',
    'Provide details' => 'Fournir des détails',
    'Provided asset' => 'COIN offertes',
    'Raised:' => 'Collecté',
    'Requested asset' => 'COIN demandées',
    'Requesting:' => 'Demande:',
    'Save' => 'Enregistrer',
    'Select asset' => 'Sélectionnez les COIN',
    'Select wanted asset' => 'Sélectionnez les COIN recherchées',
    'The assets listed below are currently wanted as crowd funding investment.' => 'Les COIN énumérées ci-dessous sont actuellement des investissements souhaités.',
    'The current balance of the funding account is:' => 'Le solde actuel du compte de financement est:',
    'Deleted Campaign' => 'Supprimée',
    'Add Your Project' => 'Ajoutez votre projet',
    'Select from which space you want to create your campaign' => 'Choisissez depuis quel espace vous souhaitrez créer votre campagne',
    'Select space' => 'Choisissez l\'espace',
    'Create new space' => 'Créez un nouveau espace',
    'Leave empty if you want to create automatically a new space for this campaign' => 'Laissez vide si vous souhaitez créer automatiquement un nouvel espace pour cette campagne',
    'Title already used' => 'Titre déjà utilisé',
    'Set funding request' => 'Définir la demande de financement',
    'Requested amount' => 'Montant demandé',
    'Title' => 'Titre de votre campagne',
    'Trusted' => 'Definir comme vérifié',
    'Untrusted' => 'Definir comme non vérifié',
    'Under review' => 'Vérification en cours',
    'Verified' => 'Vérfié',
];
