<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Currently there are no products available!' => 'Actuellement,il n y apas de produits disponibles!',
    'Discount' => 'Remise',
    'Marketplace' => '',
    'Picture' => 'Image',
    'Please choose the payment type for your product' => 'Veuillez choisir le type de paiement pour votre produit',
    'Please choose the type of coin you are accepting' => 'Veuillez choisir le type de COIN que vous acceptez',
    'Please choose the type of you offer' => 'S\'il vous plait choisir le type de votre offre',
    'Please enter a detailed description for your product' => 'Veuillez saisir une description détaillée de votre produit',
    'Please enter a price for your product' => 'Veuillez entrer un prix pour votre produit',
    'Please enter a short description for your product' => 'Veuillez saisir une bréve description pour votre produit',
    'Please enter the discount in percentage' => 'S\'il vous plait entrer la remise en pourcentage',
    'Please enter your product name' => 'S\'il vous plait enrer le nom de votre produit',
    'Price' => 'Prix',
    'Save' => 'Enregistrer',
    'Select asset' => 'Select COIN',
    'Select offer type' => 'Sélectionnez le type d\'offre',
    'Select payment type' => 'Sélectionnez le type de paiment',
    'Sell Product' => 'Offrir un produit',
    'Marketplace Portfolio' =>'Portefeuille du Marketplace',
    'List your Product/Service' => 'Listez votre produit/service'
];
