<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Marketplace</strong> Portfolio ' => '<strong>Marketplace</strong> Portfolio',
    'Add a marketplace!' => 'Ajouter un marketplace!',
    'Add your job' => 'Ajouter votre tâche',
    'Apply filter' => 'Appliquer le filtre',
    'Asset' => 'COIN',
    'Buy Product' => 'Acheter un produit',
    'Call to action' => 'Appel à l\'action',
    'Categories' => 'Catégories',
    'City:' => 'Ville',
    'Country:' => 'Pays',
    'Create Marketplace' => 'Créer un marketplace',
    'Created At' => 'Créé à',
    'Created By' => 'Créé par',
    'Currently there are no marketplaces.' => 'Actuellement, il n\'y a pas de marketplace.',
    'Currently there are no suggested products.' => 'Actuellement, il n\'y a pas de produits suggérés.',
    'Description' => 'Description',
    'Discount' => 'Remise',
    'Edit' => 'Modifier',
    'Edit Marketplace' => 'Modifier le marketplace',
    'Hide unverified Submissions' => 'Masquer les soumissions non vérifiées',
    'ID' => '',
    'In order to sell a product, there must be open marketplaces.' => 'Pour vendre un produit, il doit y avoir un marketplace ouverts.',
    'List your Product/Service' => 'Listez votre produit/service',
    'Marketplace' => 'Marketplace',
    'Marketplace Image (MAXIMUM FILE SIZE IS 500kb)' => 'Image du marketplace (TAILLE MAXIMALE DU FICHIER EST 500 Ko)',
    'Options' => '',
    'Picture' => 'Image',
    'Please choose the Offer unit for your product' => 'Veuillez choisir l\'unité d\'offre pour votre produit',
    'Please choose the type of coin you are accepting' => 'Veuillez choisir le type de COIN que vous acceptez',
    'Please choose the type of you offer' => 'S\'il vous plait choisir le type de votre offre',
    'Please enter a detailed description for your product' => 'Veuillez saisir une description détaillée de votre produit',
    'Please enter a price for your product' => 'Veuillez entrer un prix pour votre produit',
    'Please enter a short description for your product' => 'Veuillez saisir une bréve description pour votre produit',
    'Please enter product call to action button name, default is "Buy Product"' => 'Veuillez saisir le nom du bouton d\'appel à l\'action du produit, la valeur par défaut est "Acheter le produit"',
    'Please enter the discount in percentage' => 'S\'il vous plait entrer la remise en pourcentage',
    'Please enter your marketplace description' => 'Veuillez saisir la description de votre marketplace',
    'Please enter your marketplace title' => 'Veuillez saisir le titre de votre marketplace',
    'Please enter your product description' => 'Veuillez saisir la description de votre produit',
    'Please enter your product name' => 'S\'il vous plait enrer le nom de votre produit',
    'Price' => 'Prix',
    'Product(s)' => 'Produit(s)',
    'Requested coin' => 'COINs demandées',
    'Reset' => 'Réinitialiser',
    'Sales coin' => 'COINs demandées',
    'Save' => 'Enregistrer',
    'Search by keyword..' => 'Rechercher par mot-clé..',
    'Select asset' => 'Sélectionner les COIN',
    'Select coin' => 'Sélectionner les COIN',
    'Select country' => 'Sélectionner le pays',
    'Select location..' => 'Sélectionner l\'emplacement..',
    'Select offer type' => 'Sélectionnez le type d\'offre',
    'Select status' => 'Sélectionner le statut',
    'Select unit' => 'Sélectionner l\'unité',
    'Sell Product' => 'Offrir un produit',
    'Sell Your Product' => 'Vendre votre produit',
    'Sell Your Product!' => 'Vendez votre produit !',
    'Space ID' => 'ID de l\'éspace',
    'Space Marketplaces' => 'Marketplaces de l\'éspace',
    'Status' => 'Statut',
    'Suggested Jobs' => 'Emplois suggérés',
    'Suggested Products' => 'Produits suggérés',
    'Tasks Marketplace' => 'Tasks marketplace',
    'This marketplace is closed' => 'Ce marketplace est fermé',
    'Title' => 'Titre',
    'Type your city name' => 'Tapez le nom de votre ville',
    'Under review' => 'En cours de révision',
    'Verified' => 'Vérifié',
    'view all' => 'voir tout',
];
