<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Asset</strong> distribution' => '<strong>COIN</strong> distribution',
    '<strong>Latest transactions</strong> of all space owned accounts' => '<strong>Derniéres transactions</strong> de tous les comptes appartenant à l\'espace',
    '<strong>Latest transactions</strong> of all user accounts' => '<strong>Dernières transactions</strong> de tous les comptes d\'utilisateurs',
    '<strong>Latest transactions</strong> of space assets' => '<strong>Dernières transactions</strong> des COIN de cet espace',
    '<strong>Latest</strong> transactions' => '<strong>Dernières</strong> transactions',
    '<strong>Latest</strong> transactions in your accounts' => '<strong>Dernières</strong> transactions dans vos comptes',
    '<strong>Shareholder</strong> listing' => 'Liste des <strong>contributeurs</strong>',
    'Accounts of this space' => 'Comptes de cet espace',
    'Accounts of this user' => 'Compte de cet utilisateurs',
    'Back to overview' => 'Retour à l\'aperçu',
    'Buy' => '',
    'Create account' => 'Créer un compte',
    'Ethereum' => '',
    'Issue new assets' => 'Emettre de nouveaux COIN',
    'Latest account transactions' => 'Derniéres transactions sur le compte',
    'Latest asset transactions' => 'Derniéres transactions des COIN',
    'Shareholder list' => 'Liste des contributeurs',
    'Total Issued Amount' => 'Total montant émis',
    'You can buy and get instantly COINs using the button below' => '',
    'Your accounts' => 'Vos comptes',
    'Your current balance is:' => '',
    'Your purchase is being processed.. hold tight, it may take a while' => '',
    'Your purchase is not processed, an error has occurred on the bridge side' => '',
];
