<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Latest transactions' => '@@Derniéres transactions@@',
    '<strong>Asset</strong> distribution' => '<strong>Asset</strong> distribution',
    '<strong>Latest transactions</strong> of all space owned accounts' => '<strong>derniéres transactions</strong> de tous les comptes appartenant à l\'espace',
    '<strong>Latest transactions</strong> of all user accounts' => '<strong>Dernières transactions</strong> de tous les comptes d\'utilisateurs',
    '<strong>Latest transactions</strong> of space assets' => '<strong>Dernières transactions</strong> des ressources spatiales',
    '<strong>Latest</strong> transactions' => '<strong>Dernières</strong> transactions',
    '<strong>Latest</strong> transactions in your accounts' => '<strong>Dernières</strong> transactions dans vos comptes',
    '<strong>Shareholder</strong> listing' => '<strong>Actionnaire</strong> annonce',
    'Accounts of this space' => 'Comptes de cet espace',
    'Accounts of this user' => 'Compte de cet utilisateurs',
    'Back to overview' => 'Retour à l\'aperçu',
    'Create account' => 'Créer un compte',
    'If no manager is specified this account is manged by the owner or it\'s representatives.' => 'Si aucun responsable n\'est spécifié, ce compte est géré par le propriétaire ou ses représentants',
    'If no owner is specified, it is a personal account.' => 'Si aucun propriétaire n\'est spécifié, il s\'agit d\'un compte personnel',
    'Issue new assets' => 'Emettre de nouveaux actifs',
    'Latest account transactions' => 'Derniéres transactions sur le compte',
    'Latest asset transactions' => 'Derniéres transactions sur actifs',
    'Shareholder list' => 'liste des actionnaires',
    'Total Issued Amount' => 'Total montant émis',
    'Your accounts' => 'Vos comptes',
];
