<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Currently there are no products.' => 'Actuellement il n ya pas des produits',
    'Discount' => 'Remise',
    'Edit' => 'Modifier',
    'Delete' => 'Supprimer',
    'Picture' => 'Image',
    'Please choose the payment type for your product' => 'Veuillez choisir le type de paiment pour votre produit',
    'Please choose the type of coin you are accepting' => 'Veuillez choisir le type de COIN que vous acceptez',
    'Please choose the type of you offer' => 'S\'il vous plait le type de votre offre',
    'Please choose your product status' => 'Choisissez le statut de votre produit ',
    'Please enter a detailed description for your product' => 'Veuillez saisir une description détaillée de votre produit',
    'Please enter a price for your product' => 'Veuillez entrer un prix pour votre produit',
    'Please enter a short description for your product' => 'Veuillez saisir une bréve description pour votre produit',
    'Please enter the discount in percentage' => 'Veuillez saisir la réduction en pourcentage',
    'Please enter your product name' => 'S\'il vous plait entrez le nom de votre produit',
    'Price' => 'Prix',
    'Products' => 'Produits',
    'Save' => 'Enregistrer',
    'Select offer type' => 'Sélectionner le type d\'offre',
    'Sell Product' => 'Vendre un produit',
    'Sell product' => 'Vendre un produit',
    'This is the list of space products.' => 'Ceci est la liste des produits de l\'espace',
    'This is the list of your products.' => 'Ceci est la liste de vos produits',
    'Your products' => 'Vos produits',
    'Trusted' => 'Definir comme vérfié',
    'Untrusted' => 'Definir comme non vérfié',
    'Under review' => 'Vérification en cours',
    'Verified' => 'Vérfié',
    'Projects Portfolio' => 'Portfolio de projets'
];
