<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About the product' => 'A propos du produit',
    'Account' => 'Compte',
    'Buy this product' => 'Acheter ce produit',
    'By' => 'Par',
    'Category' => 'Catégorie',
    'Created by' => 'Créé par',
    'Currently there are no offered products.' => 'Actuellement, aucun produit n\'est proposé.',
    'Currently you are not offering any product.' => 'Actuellement, vous ne proposez aucun produit.',
    'Discount' => 'Remise',
    'Edit' => 'Modifier',
    'Gallery' => 'Galerie',
    'Location' => 'Emplacement',
    'Marketplace' => '',
    'Name already used' => 'Nom déjà utilisé',
    'Next' => 'Suivant',
    'No vouchers remaining' => 'Aucun coupon restant',
    'Offered products' => 'Produits proposés',
    'Partager' => 'Partager',
    'Pay now' => 'Payer maintenant',
    'Per Voucher' => 'Par coupon',
    'Please choose the Offer unit for your product' => 'Veuillez choisir l\'unité d\'offre pour votre produit',
    'Please enter a message to be sent when customer wants to buy your product' => 'Veuillez saisir un message à envoyer lorsqu\'un client souhaite acheter votre produit',
    'Please enter vouchers list separated by ";"' => 'Veuillez entrer la liste des codes des coupons séparés par ";"',
    'Please enter your product call to action link' => 'Veuillez saisir le lien d\'appel à l\'action de votre produit',
    'Please note that first picture will be used as cover (MAXIMUM FILE SIZE IS 500kb).' => 'Veuillez noter que la première photo sera utilisée comme couverture (la TAILLE MAXIMALE DU FICHIER EST DE 500 Ko).',
    'Please select a country along the entered city' => 'Veuillez sélectionner un pays',
    'Price' => 'Prix',
    'Projects Portfolio' => 'Portfolio de projets',
    'Provide details' => 'Fournir des détails',
    'Sales discussion for : {0}' => 'Discussion commerciale pour : {0}',
    'Save' => 'Enregistrer',
    'Select Account' => 'Sélectionner un compte',
    'Select country' => 'Sélectionner le pays',
    'Select marketplace' => 'Sélectionner le marketplace',
    'Select offer type' => 'Sélectionner le type d\'offre',
    'Select status' => 'Sélectionner le statut',
    'Set marketplace' => 'Choisir le marketplace',
    'Status' => 'Statut',
    'Trusted' => 'Definir comme vérfié',
    'Under review' => 'Vérification en cours',
    'Untrusted' => 'Definir comme non vérfié',
    'Verified' => 'Vérfié',
    'You have a new message from {0} {1}' => 'Vous avez un nouveau message de {0} {1}',
];
