<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Select</strong> sender account' => '<strong>Selectionner</strong> compte expéditeur',
    '<strong>Transfer</strong> asset' => '<strong> Transferer </strong> des COIN',
    '<strong>Transfer</strong> details' => '<strong >Transaction</strong> détails',
    '<strong>Transfer</strong> successfull' => '',
    'Account' => '',
    'After review and approval by challenge admin , your project will be visible in this public space' => '',
    'After review and approval by marketplace admin , your offer will be visible in this public space' => '',
    'Amount' => 'Monatant',
    'Close' => '',
    'Comment' => 'Commentaire',
    'Date' => 'Date',
    'Ethereum transaction Hash' => 'Ethereum transaction Hash',
    'Insufficient balance.' => '',
    'Pay for product' => '',
    'Recipient account' => '',
    'Requested amount' => '',
    'Select asset' => 'Sélectionner les COIN',
    'Sender account' => 'Compte expéditeur',
    'Target account' => 'Compte recepteur',
    'Transaction ID' => 'ID de transaction',
    'You and other members can see your offer on your page following the link below.From there , you can edit your project anytime' => '',
    'You and other members can see your project on your page following the link below.From there , you can edit your project anytime' => '',
    'You\'ve recieved {amount}' => '',
    'Your transfer of {amount} was successfull' => '',
    'link to blockchain transaction: ' => '',
];
