<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add users to conversation' => 'Ajouter des utilisateurs à la conversation',
    'Add user' => 'Ajouter un utilisateur',
    'Send' => 'Envoyer',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Confirmer</strong> la suppression de la conversation',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Confirmer</strong> le départ de la conversation',
    '<strong>Confirm</strong> message deletion' => '<strong>Confirmer</strong> la suppression du message',
    'Cancel' => 'Annuler',
    'Delete' => 'Supprimer',
    'Delete conversation' => 'Supprimer la conversation',
    'Do you really want to delete this conversation?' => 'Souhaitez-vous vraiment supprimer cette conversation ?',
    'Do you really want to delete this message?' => 'Souhaitez-vous vraiment supprimer ce message ?',
    'Do you really want to leave this conversation?' => 'Souhaitez-vous vraiment quitter cette conversation ?',
    'Leave' => 'Quitter',
    'Leave conversation' => 'Quitter la conversation',
    'There are no messages yet.' => 'Il n\'y a encore aucun message.',
];
