<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Xcoin</strong> module configuration' => '',
    'Account title' => '',
    'Add wanted users' => '',
    'Allow direct coin transfer' => '',
    'Basic' => '',
    'Coin transfer settings' => '',
    'Each period of time, a transaction is created to a memeber\'s account.' => '',
    'Manual' => '',
    'Scheduling' => '',
    'Select all members' => '',
    'Select users to allocate coins to' => '',
    'Space coins allocation transaction parameters' => '',
    'Space scheduled transactions parameters' => '',
    'Transaction amount' => '',
    'Transaction comment' => '',
    'Transaction period' => '',
    'When a member joins a space coins allocation transaction is created for his account.' => '',
    'Your next coin allocation run is in: ' => '',
];
