<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Crowd</strong> Funding' => '',
    '<strong>Crowd</strong> funding' => '',
    '<strong>Funding</strong> Invest' => '',
    'Add asset offer' => '',
    'Closed' => '',
    'Currently there are no open funding requests.' => '',
    'Currently there are no running crowd fundings campaigns!' => '',
    'Day left' => '',
    'Days left' => '',
    'Define exchange rate and maximum' => '',
    'Delete this exchange request' => '',
    'Determine the exchange rate for which you are willing to trade assets.' => '',
    'Edit' => '',
    'Gallery' => '',
    'Invest in this project' => '',
    'Next' => '',
    'Offering:' => '',
    'Pay now' => '',
    'Please enter your campaign deadline' => '',
    'Please enter your campaign description' => '',
    'Please enter your campaign needs & commitments' => '',
    'Please enter your campaign title' => '',
    'Please note that first picture will be used as cover for your crowdfunding campaign.' => '',
    'Project by' => '',
    'Provide details' => '',
    'Provided asset' => '',
    'Raised:' => '',
    'Requested asset' => '',
    'Requesting:' => '',
    'Save' => '',
    'Select asset' => '',
    'Select wanted asset' => '',
    'The assets listed below are currently wanted as crowd funding investment.' => '',
    'The current balance of the funding account is:' => '',
    'Deleted Campaign' => '',
    'Add Your Project' => '',
    'Select from which space you want to create your campaign' => '',
    'Select space' => '',
    'Create new space' => '',
    'Leave empty if you want to create automatically a new space for this campaign' => '',
    'Title already used' => '',
    'Set funding request' => '',
    'Requested amount' => 'Requested amount',
    'Title' => '',
    'Trusted' => '',
    'Untrusted' => '',
    'Under review' => '',
    'Verified' => '',
];
