<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Your Project' => 'أضف مشروعك',
    'Add a challenge!' => 'أضف التحدي!',
    'Challenge Image' => 'صورة التحدي',
    'Create Challenge' => 'إنشاء التحدي',
    'Created At' => 'تم الإنشاء في',
    'Created By' => 'تم الإنشاء بواسطة',
    'Currently there are no challenges.' => 'حاليا لا توجد تحديات.',
    'Currently there are no received submissions.' => 'حاليًا لا توجد إرسالات مشاريع',
    'Description' => 'الوصف',
    'Edit' => 'تحرير',
    'Edit Challenge' => 'تحرير التحدي',
    'ID' => 'المعرف',
    'Please enter your challenge description' => 'الرجاء إدخال وصف التحدي',
    'Please enter your challenge title' => 'الرجاء إدخال عنوان التحدي',
    'Received Submissions' => 'التقديمات المستلمة',
    'Requested coin' => 'العملة المطلوبة',
    'Save' => 'حفظ',
    'Select coin' => 'اختر عملة',
    'Select status' => 'تحديد الحالة',
    'Space Challenges' => 'تحديات الفضاء',
    'Space ID' => 'معرف الفضاء',
    'Status' => 'الحالة',
    'This challenge is stopped' => 'تم إيقاف هذا التحدي',
    'Title' => 'العنوان',
];
