<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Xcoin</strong> module configuration' => '<strong>Xcoin</strong> تكوين وحدة',
    'Account title' => 'عنوان الحساب',
    'Add wanted users' => 'إضافة المستخدمين المطلوبين',
    'Allow direct coin transfer' => 'السماح بالتحويل المباشر للعملة',
    'Appearance' => '',
    'Basic' => 'أساسي',
    'Coin transfer settings' => 'إعدادات تحويل العملات',
    'Each period of time, a transaction is created to a memeber\'s account.' => 'كل فترة زمنية ، يتم إنشاء معاملة لحساب عضو',
    'Enable/disable space appearance settings' => '',
    'Hide space cover' => '',
    'Manual' => 'الدليل',
    'Scheduling' => 'جدولة',
    'Select all members' => 'حدد كل الأعضاء',
    'Select users to allocate coins to' => 'حدد المستخدمين لتخصيص العملات',
    'Space coins allocation transaction parameters' => 'معلمات معاملات تخصيص عملات الفضاء',
    'Space scheduled transactions parameters' => 'معلمات المعاملات المجدولة الفضاء',
    'Transaction amount' => 'مبلغ التحويل',
    'Transaction comment' => 'تعليق التحويل',
    'Transaction period' => 'فترة التحويل',
    'Various settings for the space appearance' => '',
    'When a member joins a space coins allocation transaction is created for his account.' => ' تخصيص عملات يتم إنشاؤها لحسابه عندما ينضم أحد الأعضاء',
    'Your next coin allocation run is in: ' => 'يتم تشغيل تخصيص العملة في:',
];
