<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Experience' => 'إضافة وظيفة',
    'Are you sure about deleting this experience' => 'هل أنت متأكد من حذف هذه الوظيفة',
    'Delete Experience' => 'حذف الوظيفة',
    'Edit Experience' => 'تحرير الوظيفة',
    'Experience' => 'الخبرة',
    'Experience Start Date must be greater than End Date' => 'يجب أن يكون تاريخ البدء أكبر من تاريخ الانتهاء',
    'No experiences found.' => 'لم يتم العثور على تجارب.',
    'Provide experience details' => 'تقديم تفاصيل الوظيفة',
    'Save' => 'حفظ',
    'Select country' => 'حدد الدولة',
    'Today' => 'اليوم',
];
