<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Funding</strong> Invest' => 'الاستثمار',
    'Apply filter' => 'تطبيق عامل التصفية',
    'Asset' => 'الأصول',
    'Cancel campaign' => 'إلغاء الحملة',
    'Categories' => 'الفئات',
    'Categories:' => 'الفئات:',
    'Challenge' => 'التحدي',
    'City:' => 'المدينة',
    'Close campaign' => 'إغلاق الحملة',
    'Closed' => 'مغلق',
    'Confirm' => 'تأكيد',
    'Country:' => 'الدولة:',
    'Create Your Project!' => 'أنشئ مشروعك!',
    'Current Password' => 'كلمة السر الحالية',
    'Currently there are no submitted proposals.' => 'حاليا لا توجد مقترحات مقدمة',
    'Day left' => 'اليوم المتبقي',
    'Days left' => 'الأيام المتبقية',
    'Deleted Campaign' => 'حملات المحذوفة',
    'Edit' => 'تحرير',
    'Fund this project' => 'تمويل هذا المشروع',
    'Gallery' => 'الصور',
    'In order to create a project, there must be running challenges.' => 'من أجل إنشاء مشروع ، يجب أن تكون هناك تحديات قيد التشغيل.',
    'Investment Accepted' => 'الاستثمار مقبول',
    'Investment Restarted' => 'إعادة الاستثمار',
    'Leave empty if you want to create automatically a new space for this campaign' => 'اتركه فارغًا إذا كنت تريد إنشاء مساحة جديدة لهذه الحملة',
    'Load Wallet Private Key' => 'تحميل مفتاح المحفظة الخاص',
    'Location:' => 'الموقع:',
    'Next' => 'التالي',
    'Pay now' => 'ادفع الآن',
    'Please enter your campaign city' => 'الرجاء إدخال المدينة',
    'Please enter your campaign country' => 'الرجاء إدخال البلد',
    'Please enter your campaign deadline' => 'الرجاء إدخال الموعد النهائي',
    'Please enter your campaign description' => 'الرجاء إدخال وصف حملتك',
    'Please enter your campaign needs & commitments' => 'الرجاء إدخال احتياجات والتزامات حملتك',
    'Please enter your campaign title' => 'الرجاء إدخال عنوان حملتك',
    'Please note that first picture will be used as cover for your crowdfunding campaign.' => 'يرجى ملاحظة أنه سيتم استخدام الصورة الأولى كغطاء لحملة التمويل الجماعي الخاصة بك.',
    'Please select a country along the entered city' => 'الرجاء تحديد البلد',
    'Project by' => ' مشروع من',
    'Project(s)' => 'مشروع',
    'Provide details' => 'تقديم التفاصيل',
    'Raised:' => 'المحصل',
    'Requested amount' => 'المبلغ المطلوب',
    'Requested coin' => 'العملة المطلوبة',
    'Requesting:' => 'الطلب:',
    'Reset' => 'إعادة تعيين',
    'Restart campaign' => 'إعادة تشغيل الحملة',
    'Save' => 'حفظ',
    'Search by keyword..' => 'البحث بالكلمة المفتاحية ',
    'Select challenge' => 'حدد التحدي"',
    'Select country' => 'حدد الدولة',
    'Select from which space you want to create your campaign' => 'حدد المساحة التي تريد إنشاء حملتك منها',
    'Select location..' => 'حدد الموقع',
    'Select space' => 'حدد مساحة',
    'Set funding request' => 'تعيين طلب التمويل',
    'Submitted proposals' => 'المقترحات المقدمة',
    'Title' => 'العنوان',
    'Title already used' => 'العنوان مستخدم',
    'Trusted' => 'موثوق',
    'Type your city name' => 'اكتب اسم المدينة',
    'Under review' => 'قيد المراجعة',
    'Untrusted' => 'غير موثوق به',
    'Verified' => 'تم التحقق منه',
];
