<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add your job' => 'أضف وظيفتك',
    'Available jobs categories :' => 'فئات الوظائف المتاحة',
    'Available product categories :' => 'فئات المنتجات المتاحة',
    'List your Product/Service' => 'ضع منتجك / خدمتك',
    'List your Product/Service!' => 'ضع منتجك / خدمتك',
    'Marketplace Portfolio ' => 'منتجات السوق',
    'Options' => 'خيارات',
    'Please choose the Offer unit for your product' => 'الرجاء اختيار وحدة العرض لمنتجك',
    'Select unit' => 'حدد وحدة',
    'Suggested Jobs' => 'الوظائف المقترحة',
    'Tasks Marketplace' => 'سوق المهام',
    'Optional' => 'اختياري',
    'Please choose the payment type for your product' => 'الرجاء اختيار نوع الدفع لمنتجك',
    'Product call to action link' => 'رابط عبارة تحث المستخدم على اتخاذ إجراء',
    'Required' => 'مطلوب',
    'Select payment type' => 'حدد نوع الدفع',
    'Select product call to action link option' => 'تحديد خيار رابط الحث على اتخاذ إجراء المنتج',
    'Add a marketplace!' => 'ضف سوق',
    'Apply filter' => 'تطبيق عامل التصفية',
    'Asset' => 'الأصول',
    'Buy Product' => 'شراء',
    'Call to action' => 'دعوة للعمل',
    'Categories' => 'الفئات',
    'City:' => 'المدينة:',
    'Country:' => 'الدولة:',
    'Create Marketplace' => 'إنشاء سوق',
    'Created At' => 'تم الإنشاء في',
    'Created By' => 'تم الإنشاء بواسطة',
    'Currently there are no marketplaces.' => 'حاليا لا توجد أسواق',
    'Currently there are no suggested products.' => 'حاليا لا توجد منتجات',
    'Description' => 'الوصف',
    'Discount' => 'تخفيض',
    'Edit' => 'تحرير',
    'Edit Marketplace' => 'تحرير السوق',
    'ID' => 'المعرف',
    'In order to sell a product, there must be open marketplaces.' => 'من أجل بيع منتج ، يجب أن تكون هناك أسواق مفتوحة.',
    'Marketplace' => 'السوق',
    'Marketplace Image' => 'صورة السوق',
    'Picture' => 'صورة',
    'Please choose the type of coin you are accepting' => 'الرجاء اختيار نوع العملة التي تقبلها',
    'Please choose the type of you offer' => 'الرجاء اختيار نوع العرض',
    'Please enter a detailed description for your product' => 'الرجاء إدخال وصف تفصيلي لمنتجك',
    'Please enter a price for your product' => 'الرجاء إدخال سعر لمنتجك',
    'Please enter a short description for your product' => 'الرجاء إدخال وصف موجز لمنتجك',
    'Please enter product call to action button name, default is "Buy Product"' => 'الرجاء إدخال اسم زر استدعاء المنتج',
    'Please enter the discount in percentage' => 'الرجاء إدخال التخفيض بالنسبة المئوية',
    'Please enter your marketplace description' => 'الرجاء إدخال وصف السوق',
    'Please enter your marketplace title' => 'الرجاء إدخال عنوان السوق',
    'Please enter your product description' => 'الرجاء إدخال وصف المنتج',
    'Please enter your product name' => 'الرجاء إدخال اسم المنتج',
    'Price' => 'السعر',
    'Product(s)' => 'المنتج',
    'Requested coin' => 'العملة المطلوبة',
    'Reset' => 'إعادة تعيين',
    'Sales coin' => 'عملة المبيعات',
    'Save' => 'حفظ',
    'Search by keyword..' => 'البحث بالكلمة الرئيسية ',
    'Select asset' => 'تحديد الأصل',
    'Select coin' => 'اختر عملة',
    'Select country' => 'حدد الدولة',
    'Select location..' => 'حدد الموقع',
    'Select offer type' => 'حدد نوع العرض',
    'Select status' => 'تحديد الحالة',
    'Sell Product' => 'بيع المنتج',
    'Sell Your Product' => 'بيع منتجك',
    'Sell Your Product!' => 'بيع منتجك!',
    'Space ID' => 'معرف الفضاء',
    'Space Marketplaces' => 'أسواق الفضاء',
    'Status' => 'الحالة',
    'Suggested Products' => 'المنتجات المقترحة',
    'This marketplace is closed' => 'هذا السوق مغلق',
    'Title' => 'العنوان',
    'Type your city name' => 'اكتب اسم مدينتك',
    'Under review' => 'قيد المراجعة',
    'Verified' => 'تم التحقق منه',
];
