<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Asset</strong> distribution' => ' توزيع الأصول',
    '<strong>Latest transactions</strong> of all space owned accounts' => 'أحدث المعاملات لجميع الحسابات المملوكة للفضاء',
    '<strong>Latest transactions</strong> of all user accounts' => 'أحدث المعاملات لجميع حسابات المستخدمين',
    '<strong>Latest transactions</strong> of space assets' => 'أحدث المعاملات للأصول',
    '<strong>Latest</strong> transactions' => 'أحدث المعاملات',
    '<strong>Latest</strong> transactions in your accounts' => 'أحدث المعاملات في حساباتك',
    '<strong>Shareholder</strong> listing' => 'قائمة المساهمين',
    'Accounts of this space' => 'حسابات هذا الفضاء',
    'Accounts of this user' => 'حسابات هذا المستخدم',
    'Back to overview' => 'الرجوع إلى النظرة العامة',
    'Buy' => '',
    'Create account' => 'إنشاء حساب',
    'Ethereum' => '',
    'Issue new assets' => 'إصدار أصول جديدة',
    'Latest account transactions' => 'أحدث معاملات الحساب',
    'Latest asset transactions' => 'أحدث معاملات الأصول',
    'Shareholder list' => 'قائمة المساهمين',
    'Total Issued Amount' => 'إجمالي المبلغ المُصدر',
    'You can buy and get instantly COINs using the button below' => '',
    'Your accounts' => 'حساباتك',
    'Your current balance is:' => '',
    'Your purchase is being processed.. hold tight, it may take a while' => '',
    'Your purchase is not processed, an error has occurred on the bridge side' => '',
];
