<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Buy this product' => 'شراء هذا المنتج',
    'Categories:' => 'الفئات:',
    'Create product' => 'إنشاء منتج',
    'Create your personal product' => 'أنشئ منتجك الشخصي',
    'Currently there are no offered products.' => 'حاليا لا توجد منتجات معروضة.',
    'Currently you are not offering any product.' => 'حاليا أنت لا تقدم أي منتج.',
    'Discount' => 'تخفيض',
    'Edit' => 'تحرير',
    'Gallery' => 'الصور',
    'Leave empty if you want to create automatically a new space for this product' => 'اتركه فارغًا إذا كنت تريد إنشاء مساحة جديدة لهذا المنتج',
    'Location:' => 'الموقع:',
    'Marketplace' => 'السوق',
    'Marketplace Portfolio ' => 'محفظة السوق',
    'Name already used' => 'الاسم مستخدم',
    'Next' => 'التالي',
    'OR' => 'أو',
    'Offered products' => 'المنتجات المعروضة',
    'Owner:' => 'المالك:',
    'Please choose the payment type for your product' => 'الرجاء اختيار نوع الدفع لمنتجك',
    'Please choose the type of you offer' => 'الرجاء اختيار نوع العرض',
    'Please enter a detailed description for your product' => 'الرجاء إدخال وصف تفصيلي لمنتجك',
    'Please enter a price for your product' => 'الرجاء إدخال سعر لمنتجك',
    'Please enter a short description for your product' => 'الرجاء إدخال وصف موجز لمنتجك',
    'Please enter the discount in percentage' => 'الرجاء إدخال التخفيض بالنسبة المئوية',
    'Please enter your city' => 'اكتب اسم مدينتك',
    'Please enter your country' => 'الرجاء إدخال البلد',
    'Please enter your product call to action link' => 'رابط المنتج',
    'Please enter your product name' => 'الرجاء إدخال اسم المنتج',
    'Please note that first picture will be used as cover for your product.' => 'يرجى ملاحظة أنه سيتم استخدام الصورة الأولى كغطاء لمنتجك',
    'Please select a country along the entered city' => 'الرجاء تحديد بلد',
    'Price' => 'السعر',
    'Product by' => 'المنتج',
    'Provide details' => 'تقديم التفاصيل',
    'Save' => 'حفظ',
    'Select country' => 'حدد الدولة',
    'Select from which space you want to create your product' => 'حدد المساحة التي تريد إنشاء منتجك منها ',
    'Select marketplace' => 'حدد السوق',
    'Select offer type' => 'حدد نوع العرض',
    'Select space' => 'حدد المساحة',
    'Select status' => 'تحديد الحالة',
    'Set product marketplace' => 'تعيين سوق المنتج',
    'Status' => 'الحالة',
    'Trusted' => 'موثوق به',
    'Under review' => 'قيد المراجعة',
    'Untrusted' => 'غير موثوق به',
    'Verified' => 'تم التحقق منه',
];
