<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About the product' => '',
    'Account' => '',
    'Buy this product' => 'شراء هذا المنتج',
    'By' => 'من ',
    'Category' => '',
    'Created by' => 'تم إنشاؤه من',
    'Currently there are no offered products.' => 'حاليا لا توجد منتجات معروضة.',
    'Currently you are not offering any product.' => 'حاليا أنت لا تقدم أي منتج.',
    'Discount' => 'تخفيض',
    'Edit' => 'تحرير',
    'Gallery' => 'الصور',
    'Location' => 'الموقع',
    'Marketplace' => 'السوق',
    'Name already used' => 'الاسم مستخدم',
    'Next' => 'التالي',
    'No vouchers remaining' => '',
    'Offered products' => 'المنتجات المعروضة',
    'Partager' => '',
    'Pay now' => 'ادفع الآن',
    'Per Voucher' => '',
    'Please choose the Offer unit for your product' => 'الرجاء اختيار وحدة العرض لمنتجك',
    'Please enter a message to be sent when customer wants to buy your product' => 'الرجاء إدخال رسالة ليتم إرسالها عندما يريد العميل شراء منتجك',
    'Please enter vouchers list separated by ";"' => '',
    'Please enter your product call to action link' => 'رابط المنتج',
    'Please note that first picture will be used as cover (MAXIMUM FILE SIZE IS 500kb).' => '',
    'Please select a country along the entered city' => 'الرجاء تحديد بلد',
    'Price' => 'السعر',
    'Projects Portfolio' => 'محفظة المشاريع',
    'Provide details' => 'تقديم التفاصيل',
    'Sales discussion for : {0}' => '',
    'Save' => 'حفظ',
    'Select Account' => '',
    'Select country' => 'حدد الدولة',
    'Select marketplace' => 'حدد السوق',
    'Select offer type' => 'حدد نوع العرض',
    'Select status' => 'تحديد الحالة',
    'Set marketplace' => 'تعيين السوق',
    'Status' => 'الحالة',
    'Trusted' => 'موثوق به',
    'Under review' => 'قيد المراجعة',
    'Untrusted' => 'غير موثوق به',
    'Verified' => 'تم التحقق منه',
    'You have a new message from {0} {1}' => '',
];
