<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Select</strong> sender account' => 'حدد حساب المرسل',
    '<strong>Transfer</strong> asset' => 'تحويل الأصول',
    '<strong>Transfer</strong> details' => 'تفاصيل التحويل',
    '<strong>Transfer</strong> successfull' => '',
    'Account' => '',
    'After review and approval by challenge admin , your project will be visible in this public space' => '',
    'After review and approval by marketplace admin , your offer will be visible in this public space' => '',
    'Amount' => 'المبلغ',
    'Close' => '',
    'Comment' => 'تعليق',
    'Date' => 'التاريخ',
    'Ethereum transaction Hash' => 'تجزئة معاملات إيثيريوم',
    'Insufficient balance.' => 'رصيد غير كاف',
    'Pay for product' => 'الدفع مقابل المنتج',
    'Recipient account' => 'حساب المستلم',
    'Requested amount' => 'المبلغ المطلوب',
    'Select asset' => 'تحديد الأصل',
    'Sender account' => 'حساب المرسل',
    'Target account' => 'حساب المستلم',
    'Transaction ID' => 'معرف المعاملة',
    'You and other members can see your offer on your page following the link below.From there , you can edit your project anytime' => '',
    'You and other members can see your project on your page following the link below.From there , you can edit your project anytime' => '',
    'You\'ve recieved {amount}' => '',
    'Your transfer of {amount} was successfull' => '',
    'link to blockchain transaction: ' => '',
];
