<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Crowd</strong> Funding' => '<strong>Project</strong> funding',
    '<strong>Crowd</strong> funding' => '<strong>Project</strong> funding',
    '<strong>Funding</strong> Invest' => '',
    'Asset' => 'COIN',
    'Add asset offer' => 'Start funding campaign',
    'Closed' => '',
    'Currently there are no open funding requests.' => '',
    'Currently there are no running crowd fundings campaigns!' => '',
    'Day left' => '',
    'Days left' => '',
    'Define exchange rate and maximum' => '',
    'Delete this exchange request' => '',
    'Determine the exchange rate for which you are willing to trade assets.' => 'At which rate do you want to exchange your COINs?',
    'Edit' => '',
    'Gallery' => '',
    'Invest in this project' => 'Invest COINs to this project',
    'Next' => '',
    'Offering:' => '',
    'Pay now' => 'Allocate COINs',
    'Please enter your campaign deadline' => '',
    'Please enter your campaign description' => 'Please enter a short description of your campaign',
    'Please enter your campaign needs & commitments' => 'Please enter more details about your project',
    'Please enter your campaign title' => '',
    'Please note that first picture will be used as cover for your crowdfunding campaign.' => '',
    'Project by' => '',
    'Provide details' => '',
    'Provided asset' => 'Offered COINs',
    'Raised:' => 'Raised',
    'Requested asset' => 'Requested COINs',
    'Requesting:' => '',
    'Save' => '',
    'Select asset' => 'Select COINs',
    'Select wanted asset' => 'Select wanted COINs',
    'The assets listed below are currently wanted as crowd funding investment.' => 'The COINs listed below are currently wanted investment.',
    'The current balance of the funding account is:' => '',
    'Deleted Campaign' => 'Deleted',
    'Add Your Project' => 'Add your Project',
    'Select from which space you want to create your campaign' => 'Select from which space you want to create your campaign',
    'Select space' => 'Select space',
    'Create new space' => 'Create new space',
    'Leave empty if you want to create automatically a new space for this campaign' => 'Leave empty if you want to create automatically a new space for this campaign',
    'Title already used' => 'Title already used',
    'Set funding request' => 'Set funding request',
    'Requested amount' => 'Requested amount',
    'Title' => 'Campaign title',
    'Trusted' => 'Set to verified',
    'Untrusted' => 'Set to non verified',
    'Under review' => '',
    'Verified' => '',
];
