<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Marketplace</strong> Portfolio ' => '',
    'Add a marketplace!' => '',
    'Add your job' => '',
    'Apply filter' => '',
    'Asset' => '',
    'Buy Product' => '',
    'Call to action' => '',
    'Categories' => '',
    'City:' => '',
    'Country:' => '',
    'Create Marketplace' => '',
    'Created At' => '',
    'Created By' => '',
    'Currently there are no marketplaces.' => '',
    'Currently there are no suggested products.' => '',
    'Description' => '',
    'Discount' => '',
    'Edit' => '',
    'Edit Marketplace' => '',
    'Hide unverified Submissions' => '',
    'ID' => '',
    'In order to sell a product, there must be open marketplaces.' => '',
    'List your Product/Service' => '',
    'Marketplace' => '',
    'Marketplace Image (MAXIMUM FILE SIZE IS 500kb)' => '',
    'Options' => '',
    'Picture' => '',
    'Please choose the Offer unit for your product' => '',
    'Please choose the type of coin you are accepting' => '',
    'Please choose the type of you offer' => '',
    'Please enter a detailed description for your product' => '',
    'Please enter a price for your product' => '',
    'Please enter a short description for your product' => '',
    'Please enter product call to action button name, default is "Buy Product"' => '',
    'Please enter the discount in percentage' => '',
    'Please enter your marketplace description' => '',
    'Please enter your marketplace title' => '',
    'Please enter your product description' => '',
    'Please enter your product name' => '',
    'Price' => '',
    'Product(s)' => '',
    'Requested coin' => '',
    'Reset' => '',
    'Sales coin' => '',
    'Save' => '',
    'Search by keyword..' => '',
    'Select asset' => 'Select COIN',
    'Select coin' => '',
    'Select country' => '',
    'Select location..' => '',
    'Select offer type' => '',
    'Select status' => '',
    'Select unit' => '',
    'Sell Product' => 'Offer product',
    'Sell Your Product' => '',
    'Sell Your Product!' => '',
    'Space ID' => '',
    'Space Marketplaces' => '',
    'Status' => '',
    'Suggested Jobs' => '',
    'Suggested Products' => '',
    'Tasks Marketplace' => '',
    'This marketplace is closed' => '',
    'Title' => '',
    'Type your city name' => '',
    'Under review' => '',
    'Verified' => '',
    'view all' => '',
];
