<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Asset</strong> distribution' => '<strong>COIN</strong> owner list',
    '<strong>Latest transactions</strong> of all space owned accounts' => '',
    '<strong>Latest transactions</strong> of all user accounts' => '',
    '<strong>Latest transactions</strong> of space assets' => '<strong>Latest transactions</strong> of space COINs',
    '<strong>Latest</strong> transactions' => '',
    '<strong>Latest</strong> transactions in your accounts' => '',
    '<strong>Shareholder</strong> listing' => '<strong>Contributor</strong> list',
    'Accounts of this space' => '',
    'Accounts of this user' => '',
    'Back to overview' => '',
    'Buy' => '',
    'Create account' => '',
    'Ethereum' => '',
    'Issue new assets' => 'Create new COINs',
    'Latest account transactions' => '',
    'Latest asset transactions' => 'Latest COIN transactions',
    'Shareholder list' => 'Contributor list',
    'Total Issued Amount' => '',
    'You can buy and get instantly COINs using the button below' => '',
    'Your accounts' => '',
    'Your current balance is:' => '',
    'Your purchase is being processed.. hold tight, it may take a while' => '',
    'Your purchase is not processed, an error has occurred on the bridge side' => '',
];
