<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Latest transactions</strong> of all space owned accounts' => '',
    '<strong>Latest transactions</strong> of all user accounts' => '',
    '<strong>Latest</strong> transactions' => '',
    '<strong>Latest</strong> transactions in your accounts' => '',
    'Accounts of this space' => '',
    'Accounts of this user' => '',
    'Back to overview' => '',
    'Create account' => '',
    'If no manager is specified this account is manged by the owner or it\'s representatives.' => '',
    'If no owner is specified, it is a personal account.' => '',
    'Latest account transactions' => '',
    'Total Issued Amount' => '',
    'Your accounts' => '',
    'Latest transactions' => '@@@@',
    '<strong>Asset</strong> distribution' => '<strong>Coin</strong> owner list',
    '<strong>Latest transactions</strong> of space assets' => '<strong>Latest transactions</strong> of space coins',
    '<strong>Shareholder</strong> listing' => '<strong>Contributor</strong> list',
    'Issue new assets' => 'Create new coins',
    'Latest asset transactions' => 'Latest coin transactions',
    'Shareholder list' => 'Contribution list',
];
