<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Currently there are no products.' => '',
    'Discount' => '',
    'Edit' => '',
    'Picture' => '',
    'Please choose the payment type for your product' => '',
    'Please choose the type of coin you are accepting' => '',
    'Please choose the type of you offer' => '',
    'Please choose your product status' => '',
    'Please enter a detailed description for your product' => '',
    'Please enter a price for your product' => '',
    'Please enter a short description for your product' => '',
    'Please enter the discount in percentage' => '',
    'Please enter your product name' => '',
    'Price' => '',
    'Products' => '',
    'Save' => '',
    'Select offer type' => '',
    'Sell Product' => '',
    'Sell product' => '',
    'This is the list of space products.' => '',
    'This is the list of your products.' => '',
    'Your products' => '',
];
