<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About the product' => '',
    'Account' => '',
    'Buy this product' => '',
    'By' => '',
    'Category' => '',
    'Created by' => '',
    'Currently there are no offered products.' => '',
    'Currently you are not offering any product.' => '',
    'Discount' => '',
    'Edit' => '',
    'Gallery' => '',
    'Location' => '',
    'Marketplace' => '',
    'Name already used' => '',
    'Next' => '',
    'No vouchers remaining' => '',
    'Offered products' => '',
    'Partager' => '',
    'Pay now' => '',
    'Per Voucher' => '',
    'Please choose the Offer unit for your product' => '',
    'Please enter a message to be sent when customer wants to buy your product' => '',
    'Please enter vouchers list separated by ";"' => '',
    'Please enter your product call to action link' => '',
    'Please note that first picture will be used as cover (MAXIMUM FILE SIZE IS 500kb).' => '',
    'Please select a country along the entered city' => '',
    'Price' => '',
    'Projects Portfolio' => '',
    'Provide details' => '',
    'Sales discussion for : {0}' => '',
    'Save' => '',
    'Select Account' => '',
    'Select country' => '',
    'Select marketplace' => '',
    'Select offer type' => '',
    'Select status' => '',
    'Set marketplace' => '',
    'Status' => '',
    'Trusted' => 'Set to verified',
    'Under review' => '',
    'Untrusted' => 'Set to non verified',
    'Verified' => '',
    'You have a new message from {0} {1}' => '',
];
